In [1]:
import numpy as np
import seaborn as sns
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

## Görev 1: Seaborn kütüphanesi içerisinden Titanic veri setini tanımlayınız.

In [2]:
df = sns.load_dataset("titanic")  # Not: repodaki titanic.csv Kaggle stili kolonlar iceriyor (Sex, Survived...) ve "who"/"deck"/"embark_town" gibi bu script'in bekledigi turetilmis kolonlari icermiyor. Script'in orijinal olarak yazildigi seaborn semasiyla (kucuk harfli + turetilmis kolonlar) birebir eslesmesi icin sns.load_dataset("titanic") kullanildi.
df.head()
df.shape

(891, 15)

## Görev 2: Yukarıda tanımlanan Titanic veri setindeki kadın ve erkek yolcuların sayısını bulunuz.

In [3]:
df["sex"].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

## Görev 3: Her bir sutuna ait unique değerlerin sayısını bulunuz.

In [4]:
df.nunique()

survived         2
pclass           3
sex              2
age             88
sibsp            7
parch            7
fare           248
embarked         3
class            3
who              3
adult_male       2
deck             7
embark_town      3
alive            2
alone            2
dtype: int64

## Görev 4: pclass değişkeninin unique değerleri bulunuz.

In [5]:
df.loc[:, "pclass"].unique()

df["pclass"].unique()

array([3, 1, 2])

## Görev 5:  pclass ve parch değişkenlerinin unique değerlerinin sayısını bulunuz.

In [6]:
df.loc[:, ["pclass", "parch"]].nunique()

pclass    3
parch     7
dtype: int64

## Görev 6: embarked değişkeninin tipini kontrol ediniz. Tipini category olarak değiştiriniz. Tekrar tipini kontrol ediniz.

In [7]:
df["embarked"].dtype
str(df["embarked"].dtype)
df["embarked"] = df["embarked"].astype("category")
str(df["embarked"].dtype)

# OBJECT
# Out[16]: array(['S', 'C', 'Q', nan], dtype=object)

# CATEGORY
# ['S', 'C', 'Q', NaN]
# Categories (3, object): ['C', 'Q', 'S']
# df.loc[df["embarked"] == "S", "embarked"] = "A"  # değiştirmeye çalışmak hata verecektir

'category'

## Görev 7: embarked değeri C olanların tüm bilgilerini gösteriniz.

In [8]:
# df[df["embarked"] == "C"]
df.loc[df["embarked"] == "C"]

     survived  pclass     sex    age  sibsp  parch      fare embarked   class    who  adult_male deck embark_town alive  alone
1           1       1  female  38.00      1      0   71.2833        C   First  woman       False    C   Cherbourg   yes  False
9           1       2  female  14.00      1      0   30.0708        C  Second  child       False  NaN   Cherbourg   yes  False
19          1       3  female    NaN      0      0    7.2250        C   Third  woman       False  NaN   Cherbourg   yes   True
26          0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
30          0       1    male  40.00      0      0   27.7208        C   First    man        True  NaN   Cherbourg    no   True
31          1       1  female    NaN      1      0  146.5208        C   First  woman       False    B   Cherbourg   yes  False
34          0       1    male  28.00      1      0   82.1708        C   First    man        True  NaN   Cherbourg    no  False
36          1       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN   Cherbourg   yes   True
39          1       3  female  14.00      1      0   11.2417        C   Third  child       False  NaN   Cherbourg   yes  False
42          0       3    male    NaN      0      0    7.8958        C   Third    man        True  NaN   Cherbourg    no   True
43          1       2  female   3.00      1      2   41.5792        C  Second  child       False  NaN   Cherbourg   yes  False
48          0       3    male    NaN      2      0   21.6792        C   Third    man        True  NaN   Cherbourg    no  False
52          1       1  female  49.00      1      0   76.7292        C   First  woman       False    D   Cherbourg   yes  False
54          0       1    male  65.00      0      1   61.9792        C   First    man        True    B   Cherbourg    no  False
57          0       3    male  28.50      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
60          0       3    male  22.00      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
64          0       1    male    NaN      0      0   27.7208        C   First    man        True  NaN   Cherbourg    no   True
65          1       3    male    NaN      1      1   15.2458        C   Third    man        True  NaN   Cherbourg   yes  False
73          0       3    male  26.00      1      0   14.4542        C   Third    man        True  NaN   Cherbourg    no  False
96          0       1    male  71.00      0      0   34.6542        C   First    man        True    A   Cherbourg    no   True
97          1       1    male  23.00      0      1   63.3583        C   First    man        True    D   Cherbourg   yes  False
111         0       3  female  14.50      1      0   14.4542        C   Third  child       False  NaN   Cherbourg    no  False
114         0       3  female  17.00      0      0   14.4583        C   Third  woman       False  NaN   Cherbourg    no   True
118         0       1    male  24.00      0      1  247.5208        C   First    man        True    B   Cherbourg    no  False
122         0       2    male  32.50      1      0   30.0708        C  Second    man        True  NaN   Cherbourg    no  False
125         1       3    male  12.00      1      0   11.2417        C   Third  child       False  NaN   Cherbourg   yes  False
128         1       3  female    NaN      1      1   22.3583        C   Third  woman       False    F   Cherbourg   yes  False
130         0       3    male  33.00      0      0    7.8958        C   Third    man        True  NaN   Cherbourg    no   True
135         0       2    male  23.00      0      0   15.0458        C  Second    man        True  NaN   Cherbourg    no   True
139         0       1    male  24.00      0      0   79.2000        C   First    man        True    B   Cherbourg    no   True
140         0       3  female    NaN      0      2   15.2458        C   Third  woman       False  NaN   Cherbourg    no  False
155         0       1    male  51.00      0      1   61.3792        C   First    man        True  NaN   Cherbourg    no  False
174         0       1    male  56.00      0      0   30.6958        C   First    man        True    A   Cherbourg    no   True
177         0       1  female  50.00      0      0   28.7125        C   First  woman       False    C   Cherbourg    no   True
181         0       2    male    NaN      0      0   15.0500        C  Second    man        True  NaN   Cherbourg    no   True
194         1       1  female  44.00      0      0   27.7208        C   First  woman       False    B   Cherbourg   yes   True
195         1       1  female  58.00      0      0  146.5208        C   First  woman       False    B   Cherbourg   yes   True
203         0       3    male  45.50      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
207         1       3    male  26.00      0      0   18.7875        C   Third    man        True  NaN   Cherbourg   yes   True
209         1       1    male  40.00      0      0   31.0000        C   First    man        True    A   Cherbourg   yes   True
215         1       1  female  31.00      1      0  113.2750        C   First  woman       False    D   Cherbourg   yes  False
218         1       1  female  32.00      0      0   76.2917        C   First  woman       False    D   Cherbourg   yes   True
240         0       3  female    NaN      1      0   14.4542        C   Third  woman       False  NaN   Cherbourg    no  False
244         0       3    male  30.00      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
255         1       3  female  29.00      0      2   15.2458        C   Third  woman       False  NaN   Cherbourg   yes  False
256         1       1  female    NaN      0      0   79.2000        C   First  woman       False  NaN   Cherbourg   yes   True
258         1       1  female  35.00      0      0  512.3292        C   First  woman       False  NaN   Cherbourg   yes   True
273         0       1    male  37.00      0      1   29.7000        C   First    man        True    C   Cherbourg    no  False
285         0       3    male  33.00      0      0    8.6625        C   Third    man        True  NaN   Cherbourg    no   True
291         1       1  female  19.00      1      0   91.0792        C   First  woman       False    B   Cherbourg   yes  False
292         0       2    male  36.00      0      0   12.8750        C  Second    man        True    D   Cherbourg    no   True
295         0       1    male    NaN      0      0   27.7208        C   First    man        True  NaN   Cherbourg    no   True
296         0       3    male  23.50      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
299         1       1  female  50.00      0      1  247.5208        C   First  woman       False    B   Cherbourg   yes  False
306         1       1  female    NaN      0      0  110.8833        C   First  woman       False  NaN   Cherbourg   yes   True
307         1       1  female  17.00      1      0  108.9000        C   First  woman       False    C   Cherbourg   yes  False
308         0       2    male  30.00      1      0   24.0000        C  Second    man        True  NaN   Cherbourg    no  False
309         1       1  female  30.00      0      0   56.9292        C   First  woman       False    E   Cherbourg   yes   True
310         1       1  female  24.00      0      0   83.1583        C   First  woman       False    C   Cherbourg   yes   True
311         1       1  female  18.00      2      2  262.3750        C   First  woman       False    B   Cherbourg   yes  False
319         1       1  female  40.00      1      1  134.5000        C   First  woman       False    E   Cherbourg   yes  False
325         1       1  female  36.00      0      0  135.6333        C   First  woman       False    C   Cherbourg   yes   True
329         1       1  female  16.00      0      1   57.9792        C   First  woman       False    B   Cherbourg   yes  False
337         1       1  female  41.00      0      0  134.5000        C   First  woman       False    E   Cherbourg   yes   True
352         0       3    male  15.00      1      1    7.2292        C   Third  child       False  NaN   Cherbourg    no  False
354         0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
361         0       2    male  29.00      1      0   27.7208        C  Second    man        True  NaN   Cherbourg    no  False
362         0       3  female  45.00      0      1   14.4542        C   Third  woman       False  NaN   Cherbourg    no  False
366         1       1  female  60.00      1      0   75.2500        C   First  woman       False    D   Cherbourg   yes  False
367         1       3  female    NaN      0      0    7.2292        C   Third  woman       False  NaN   Cherbourg   yes   True
369         1       1  female  24.00      0      0   69.3000        C   First  woman       False    B   Cherbourg   yes   True
370         1       1    male  25.00      1      0   55.4417        C   First    man        True    E   Cherbourg   yes  False
373         0       1    male  22.00      0      0  135.6333        C   First    man        True  NaN   Cherbourg    no   True
375         1       1  female    NaN      1      0   82.1708        C   First  woman       False  NaN   Cherbourg   yes  False
377         0       1    male  27.00      0      2  211.5000        C   First    man        True    C   Cherbourg    no  False
378         0       3    male  20.00      0      0    4.0125        C   Third    man        True  NaN   Cherbourg    no   True
380         1       1  female  42.00      0      0  227.5250        C   First  woman       False  NaN   Cherbourg   yes   True
381         1       3  female   1.00      0      2   15.7417        C   Third  child       False  NaN   Cherbourg   yes  False
389         1       2  female  17.00      0      0   12.0000        C  Second  woman       False  NaN   Cherbourg   yes   True
393         1       1  female  23.00      1      0  113.2750        C   First  woman       False    D   Cherbourg   yes  False
420         0       3    male    NaN      0      0    7.8958        C   Third    man        True  NaN   Cherbourg    no   True
448         1       3  female   5.00      2      1   19.2583        C   Third  child       False  NaN   Cherbourg   yes  False
452         0       1    male  30.00      0      0   27.7500        C   First    man        True    C   Cherbourg    no   True
453         1       1    male  49.00      1      0   89.1042        C   First    man        True    C   Cherbourg   yes  False
455         1       3    male  29.00      0      0    7.8958        C   Third    man        True  NaN   Cherbourg   yes   True
469         1       3  female   0.75      2      1   19.2583        C   Third  child       False  NaN   Cherbourg   yes  False
473         1       2  female  23.00      0      0   13.7917        C  Second  woman       False    D   Cherbourg   yes   True
484         1       1    male  25.00      1      0   91.0792        C   First    man        True    B   Cherbourg   yes  False
487         0       1    male  58.00      0      0   29.7000        C   First    man        True    B   Cherbourg    no   True
493         0       1    male  71.00      0      0   49.5042        C   First    man        True  NaN   Cherbourg    no   True
495         0       3    male    NaN      0      0   14.4583        C   Third    man        True  NaN   Cherbourg    no   True
496         1       1  female  54.00      1      0   78.2667        C   First  woman       False    D   Cherbourg   yes  False
505         0       1    male  18.00      1      0  108.9000        C   First    man        True    C   Cherbourg    no  False
513         1       1  female  54.00      1      0   59.4000        C   First  woman       False  NaN   Cherbourg   yes  False
522         0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
523         1       1  female  44.00      0      1   57.9792        C   First  woman       False    B   Cherbourg   yes  False
524         0       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
531         0       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
532         0       3    male  17.00      1      1    7.2292        C   Third    man        True  NaN   Cherbourg    no  False
533         1       3  female    NaN      0      2   22.3583        C   Third  woman       False  NaN   Cherbourg   yes  False
537         1       1  female  30.00      0      0  106.4250        C   First  woman       False  NaN   Cherbourg   yes   True
539         1       1  female  22.00      0      2   49.5000        C   First  woman       False    B   Cherbourg   yes  False
544         0       1    male  50.00      1      0  106.4250        C   First    man        True    C   Cherbourg    no  False
547         1       2    male    NaN      0      0   13.8625        C  Second    man        True  NaN   Cherbourg   yes   True
550         1       1    male  17.00      0      2  110.8833        C   First    man        True    C   Cherbourg   yes  False
553         1       3    male  22.00      0      0    7.2250        C   Third    man        True  NaN   Cherbourg   yes   True
556         1       1  female  48.00      1      0   39.6000        C   First  woman       False    A   Cherbourg   yes  False
557         0       1    male    NaN      0      0  227.5250        C   First    man        True  NaN   Cherbourg    no   True
568         0       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
578         0       3  female    NaN      1      0   14.4583        C   Third  woman       False  NaN   Cherbourg    no  False
581         1       1  female  39.00      1      1  110.8833        C   First  woman       False    C   Cherbourg   yes  False
583         0       1    male  36.00      0      0   40.1250        C   First    man        True    A   Cherbourg    no   True
584         0       3    male    NaN      0      0    8.7125        C   Third    man        True  NaN   Cherbourg    no   True
587         1       1    male  60.00      1      1   79.2000        C   First    man        True    B   Cherbourg   yes  False
591         1       1  female  52.00      1      0   78.2667        C   First  woman       False    D   Cherbourg   yes  False
598         0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
599         1       1    male  49.00      1      0   56.9292        C   First    man        True    A   Cherbourg   yes  False
604         1       1    male  35.00      0      0   26.5500        C   First    man        True  NaN   Cherbourg   yes   True
608         1       2  female  22.00      1      2   41.5792        C  Second  woman       False  NaN   Cherbourg   yes  False
620         0       3    male  27.00      1      0   14.4542        C   Third    man        True  NaN   Cherbourg    no  False
622         1       3    male  20.00      1      1   15.7417        C   Third    man        True  NaN   Cherbourg   yes  False
632         1       1    male  32.00      0      0   30.5000        C   First    man        True    B   Cherbourg   yes   True
641         1       1  female  24.00      0      0   69.3000        C   First  woman       False    B   Cherbourg   yes   True
644         1       3  female   0.75      2      1   19.2583        C   Third  child       False  NaN   Cherbourg   yes  False
645         1       1    male  48.00      1      0   76.7292        C   First    man        True    D   Cherbourg   yes  False
647         1       1    male  56.00      0      0   35.5000        C   First    man        True    A   Cherbourg   yes   True
659         0       1    male  58.00      0      2  113.2750        C   First    man        True    D   Cherbourg    no  False
661         0       3    male  40.00      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
679         1       1    male  36.00      0      1  512.3292        C   First    man        True    B   Cherbourg   yes  False
681         1       1    male  27.00      0      0   76.7292        C   First    man        True    D   Cherbourg   yes   True
685         0       2    male  25.00      1      2   41.5792        C  Second    man        True  NaN   Cherbourg    no  False
691         1       3  female   4.00      0      1   13.4167        C   Third  child       False  NaN   Cherbourg   yes  False
693         0       3    male  25.00      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
698         0       1    male  49.00      1      1  110.8833        C   First    man        True    C   Cherbourg    no  False
700         1       1  female  18.00      1      0  227.5250        C   First  woman       False    C   Cherbourg   yes  False
702         0       3  female  18.00      0      1   14.4542        C   Third  woman       False  NaN   Cherbourg    no  False
709         1       3    male    NaN      1      1   15.2458        C   Third    man        True  NaN   Cherbourg   yes  False
710         1       1  female  24.00      0      0   49.5042        C   First  woman       False    C   Cherbourg   yes   True
716         1       1  female  38.00      0      0  227.5250        C   First  woman       False    C   Cherbourg   yes   True
731         0       3    male  11.00      0      0   18.7875        C   Third  child       False  NaN   Cherbourg    no   True
737         1       1    male  35.00      0      0  512.3292        C   First    man        True    B   Cherbourg   yes   True
742         1       1  female  21.00      2      2  262.3750        C   First  woman       False    B   Cherbourg   yes  False
762         1       3    male  20.00      0      0    7.2292        C   Third    man        True  NaN   Cherbourg   yes   True
766         0       1    male    NaN      0      0   39.6000        C   First    man        True  NaN   Cherbourg    no   True
773         0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
780         1       3  female  13.00      0      0    7.2292        C   Third  child       False  NaN   Cherbourg   yes   True
789         0       1    male  46.00      0      0   79.2000        C   First    man        True    B   Cherbourg    no   True
793         0       1    male    NaN      0      0   30.6958        C   First    man        True  NaN   Cherbourg    no   True
798         0       3    male  30.00      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
803         1       3    male   0.42      0      1    8.5167        C   Third  child       False  NaN   Cherbourg   yes  False
817         0       2    male  31.00      1      1   37.0042        C  Second    man        True  NaN   Cherbourg    no  False
827         1       2    male   1.00      0      2   37.0042        C  Second  child       False  NaN   Cherbourg   yes  False
830         1       3  female  15.00      1      0   14.4542        C   Third  child       False  NaN   Cherbourg   yes  False
832         0       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
835         1       1  female  39.00      1      1   83.1583        C   First  woman       False    E   Cherbourg   yes  False
839         1       1    male    NaN      0      0   29.7000        C   First    man        True    C   Cherbourg   yes   True

## BONUS

In [9]:
df.loc[df["embarked"].str.contains("c", na=False, case=False)]

df.loc[(df["embarked"] == "C") | (df["embarked"] == "S")].head()
df.loc[df["embarked"].isin(["C", "S"])].head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone
0         0       3    male  22.0      1      0   7.2500        S  Third    man        True  NaN  Southampton    no  False
1         1       1  female  38.0      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False
2         1       3  female  26.0      0      0   7.9250        S  Third  woman       False  NaN  Southampton   yes   True
3         1       1  female  35.0      1      0  53.1000        S  First  woman       False    C  Southampton   yes  False
4         0       3    male  35.0      0      0   8.0500        S  Third    man        True  NaN  Southampton    no   True

## Görev 8: embarked değeri S olmayanların tüm bilgilerini gösteriniz.

In [10]:
# df[df["embarked"] != "S"]
df.loc[df["embarked"] != "S"]

# 2. YOL
# df[~(df["embarked"] == "S")]
df.loc[~(df["embarked"] == "S")]

# df.loc[ ~(df["embarked"].str.contains("S", na=False)) ]

     survived  pclass     sex    age  sibsp  parch      fare embarked   class    who  adult_male deck embark_town alive  alone
1           1       1  female  38.00      1      0   71.2833        C   First  woman       False    C   Cherbourg   yes  False
5           0       3    male    NaN      0      0    8.4583        Q   Third    man        True  NaN  Queenstown    no   True
9           1       2  female  14.00      1      0   30.0708        C  Second  child       False  NaN   Cherbourg   yes  False
16          0       3    male   2.00      4      1   29.1250        Q   Third  child       False  NaN  Queenstown    no  False
19          1       3  female    NaN      0      0    7.2250        C   Third  woman       False  NaN   Cherbourg   yes   True
22          1       3  female  15.00      0      0    8.0292        Q   Third  child       False  NaN  Queenstown   yes   True
26          0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
28          1       3  female    NaN      0      0    7.8792        Q   Third  woman       False  NaN  Queenstown   yes   True
30          0       1    male  40.00      0      0   27.7208        C   First    man        True  NaN   Cherbourg    no   True
31          1       1  female    NaN      1      0  146.5208        C   First  woman       False    B   Cherbourg   yes  False
32          1       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown   yes   True
34          0       1    male  28.00      1      0   82.1708        C   First    man        True  NaN   Cherbourg    no  False
36          1       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN   Cherbourg   yes   True
39          1       3  female  14.00      1      0   11.2417        C   Third  child       False  NaN   Cherbourg   yes  False
42          0       3    male    NaN      0      0    7.8958        C   Third    man        True  NaN   Cherbourg    no   True
43          1       2  female   3.00      1      2   41.5792        C  Second  child       False  NaN   Cherbourg   yes  False
44          1       3  female  19.00      0      0    7.8792        Q   Third  woman       False  NaN  Queenstown   yes   True
46          0       3    male    NaN      1      0   15.5000        Q   Third    man        True  NaN  Queenstown    no  False
47          1       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown   yes   True
48          0       3    male    NaN      2      0   21.6792        C   Third    man        True  NaN   Cherbourg    no  False
52          1       1  female  49.00      1      0   76.7292        C   First  woman       False    D   Cherbourg   yes  False
54          0       1    male  65.00      0      1   61.9792        C   First    man        True    B   Cherbourg    no  False
57          0       3    male  28.50      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
60          0       3    male  22.00      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
61          1       1  female  38.00      0      0   80.0000      NaN   First  woman       False    B         NaN   yes   True
64          0       1    male    NaN      0      0   27.7208        C   First    man        True  NaN   Cherbourg    no   True
65          1       3    male    NaN      1      1   15.2458        C   Third    man        True  NaN   Cherbourg   yes  False
73          0       3    male  26.00      1      0   14.4542        C   Third    man        True  NaN   Cherbourg    no  False
82          1       3  female    NaN      0      0    7.7875        Q   Third  woman       False  NaN  Queenstown   yes   True
96          0       1    male  71.00      0      0   34.6542        C   First    man        True    A   Cherbourg    no   True
97          1       1    male  23.00      0      1   63.3583        C   First    man        True    D   Cherbourg   yes  False
109         1       3  female    NaN      1      0   24.1500        Q   Third  woman       False  NaN  Queenstown   yes  False
111         0       3  female  14.50      1      0   14.4542        C   Third  child       False  NaN   Cherbourg    no  False
114         0       3  female  17.00      0      0   14.4583        C   Third  woman       False  NaN   Cherbourg    no   True
116         0       3    male  70.50      0      0    7.7500        Q   Third    man        True  NaN  Queenstown    no   True
118         0       1    male  24.00      0      1  247.5208        C   First    man        True    B   Cherbourg    no  False
122         0       2    male  32.50      1      0   30.0708        C  Second    man        True  NaN   Cherbourg    no  False
125         1       3    male  12.00      1      0   11.2417        C   Third  child       False  NaN   Cherbourg   yes  False
126         0       3    male    NaN      0      0    7.7500        Q   Third    man        True  NaN  Queenstown    no   True
128         1       3  female    NaN      1      1   22.3583        C   Third  woman       False    F   Cherbourg   yes  False
130         0       3    male  33.00      0      0    7.8958        C   Third    man        True  NaN   Cherbourg    no   True
135         0       2    male  23.00      0      0   15.0458        C  Second    man        True  NaN   Cherbourg    no   True
139         0       1    male  24.00      0      0   79.2000        C   First    man        True    B   Cherbourg    no   True
140         0       3  female    NaN      0      2   15.2458        C   Third  woman       False  NaN   Cherbourg    no  False
143         0       3    male  19.00      0      0    6.7500        Q   Third    man        True  NaN  Queenstown    no   True
155         0       1    male  51.00      0      1   61.3792        C   First    man        True  NaN   Cherbourg    no  False
156         1       3  female  16.00      0      0    7.7333        Q   Third  woman       False  NaN  Queenstown   yes   True
171         0       3    male   4.00      4      1   29.1250        Q   Third  child       False  NaN  Queenstown    no  False
174         0       1    male  56.00      0      0   30.6958        C   First    man        True    A   Cherbourg    no   True
177         0       1  female  50.00      0      0   28.7125        C   First  woman       False    C   Cherbourg    no   True
181         0       2    male    NaN      0      0   15.0500        C  Second    man        True  NaN   Cherbourg    no   True
186         1       3  female    NaN      1      0   15.5000        Q   Third  woman       False  NaN  Queenstown   yes  False
188         0       3    male  40.00      1      1   15.5000        Q   Third    man        True  NaN  Queenstown    no  False
194         1       1  female  44.00      0      0   27.7208        C   First  woman       False    B   Cherbourg   yes   True
195         1       1  female  58.00      0      0  146.5208        C   First  woman       False    B   Cherbourg   yes   True
196         0       3    male    NaN      0      0    7.7500        Q   Third    man        True  NaN  Queenstown    no   True
198         1       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown   yes   True
203         0       3    male  45.50      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
207         1       3    male  26.00      0      0   18.7875        C   Third    man        True  NaN   Cherbourg   yes   True
208         1       3  female  16.00      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown   yes   True
209         1       1    male  40.00      0      0   31.0000        C   First    man        True    A   Cherbourg   yes   True
214         0       3    male    NaN      1      0    7.7500        Q   Third    man        True  NaN  Queenstown    no  False
215         1       1  female  31.00      1      0  113.2750        C   First  woman       False    D   Cherbourg   yes  False
218         1       1  female  32.00      0      0   76.2917        C   First  woman       False    D   Cherbourg   yes   True
240         0       3  female    NaN      1      0   14.4542        C   Third  woman       False  NaN   Cherbourg    no  False
241         1       3  female    NaN      1      0   15.5000        Q   Third  woman       False  NaN  Queenstown   yes  False
244         0       3    male  30.00      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
245         0       1    male  44.00      2      0   90.0000        Q   First    man        True    C  Queenstown    no  False
255         1       3  female  29.00      0      2   15.2458        C   Third  woman       False  NaN   Cherbourg   yes  False
256         1       1  female    NaN      0      0   79.2000        C   First  woman       False  NaN   Cherbourg   yes   True
258         1       1  female  35.00      0      0  512.3292        C   First  woman       False  NaN   Cherbourg   yes   True
260         0       3    male    NaN      0      0    7.7500        Q   Third    man        True  NaN  Queenstown    no   True
264         0       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown    no   True
273         0       1    male  37.00      0      1   29.7000        C   First    man        True    C   Cherbourg    no  False
274         1       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown   yes   True
278         0       3    male   7.00      4      1   29.1250        Q   Third  child       False  NaN  Queenstown    no  False
280         0       3    male  65.00      0      0    7.7500        Q   Third    man        True  NaN  Queenstown    no   True
285         0       3    male  33.00      0      0    8.6625        C   Third    man        True  NaN   Cherbourg    no   True
289         1       3  female  22.00      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown   yes   True
291         1       1  female  19.00      1      0   91.0792        C   First  woman       False    B   Cherbourg   yes  False
292         0       2    male  36.00      0      0   12.8750        C  Second    man        True    D   Cherbourg    no   True
295         0       1    male    NaN      0      0   27.7208        C   First    man        True  NaN   Cherbourg    no   True
296         0       3    male  23.50      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
299         1       1  female  50.00      0      1  247.5208        C   First  woman       False    B   Cherbourg   yes  False
300         1       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown   yes   True
301         1       3    male    NaN      2      0   23.2500        Q   Third    man        True  NaN  Queenstown   yes  False
303         1       2  female    NaN      0      0   12.3500        Q  Second  woman       False    E  Queenstown   yes   True
306         1       1  female    NaN      0      0  110.8833        C   First  woman       False  NaN   Cherbourg   yes   True
307         1       1  female  17.00      1      0  108.9000        C   First  woman       False    C   Cherbourg   yes  False
308         0       2    male  30.00      1      0   24.0000        C  Second    man        True  NaN   Cherbourg    no  False
309         1       1  female  30.00      0      0   56.9292        C   First  woman       False    E   Cherbourg   yes   True
310         1       1  female  24.00      0      0   83.1583        C   First  woman       False    C   Cherbourg   yes   True
311         1       1  female  18.00      2      2  262.3750        C   First  woman       False    B   Cherbourg   yes  False
319         1       1  female  40.00      1      1  134.5000        C   First  woman       False    E   Cherbourg   yes  False
322         1       2  female  30.00      0      0   12.3500        Q  Second  woman       False  NaN  Queenstown   yes   True
325         1       1  female  36.00      0      0  135.6333        C   First  woman       False    C   Cherbourg   yes   True
329         1       1  female  16.00      0      1   57.9792        C   First  woman       False    B   Cherbourg   yes  False
330         1       3  female    NaN      2      0   23.2500        Q   Third  woman       False  NaN  Queenstown   yes  False
337         1       1  female  41.00      0      0  134.5000        C   First  woman       False    E   Cherbourg   yes   True
352         0       3    male  15.00      1      1    7.2292        C   Third  child       False  NaN   Cherbourg    no  False
354         0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
358         1       3  female    NaN      0      0    7.8792        Q   Third  woman       False  NaN  Queenstown   yes   True
359         1       3  female    NaN      0      0    7.8792        Q   Third  woman       False  NaN  Queenstown   yes   True
361         0       2    male  29.00      1      0   27.7208        C  Second    man        True  NaN   Cherbourg    no  False
362         0       3  female  45.00      0      1   14.4542        C   Third  woman       False  NaN   Cherbourg    no  False
364         0       3    male    NaN      1      0   15.5000        Q   Third    man        True  NaN  Queenstown    no  False
366         1       1  female  60.00      1      0   75.2500        C   First  woman       False    D   Cherbourg   yes  False
367         1       3  female    NaN      0      0    7.2292        C   Third  woman       False  NaN   Cherbourg   yes   True
368         1       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown   yes   True
369         1       1  female  24.00      0      0   69.3000        C   First  woman       False    B   Cherbourg   yes   True
370         1       1    male  25.00      1      0   55.4417        C   First    man        True    E   Cherbourg   yes  False
373         0       1    male  22.00      0      0  135.6333        C   First    man        True  NaN   Cherbourg    no   True
375         1       1  female    NaN      1      0   82.1708        C   First  woman       False  NaN   Cherbourg   yes  False
377         0       1    male  27.00      0      2  211.5000        C   First    man        True    C   Cherbourg    no  False
378         0       3    male  20.00      0      0    4.0125        C   Third    man        True  NaN   Cherbourg    no   True
380         1       1  female  42.00      0      0  227.5250        C   First  woman       False  NaN   Cherbourg   yes   True
381         1       3  female   1.00      0      2   15.7417        C   Third  child       False  NaN   Cherbourg   yes  False
388         0       3    male    NaN      0      0    7.7292        Q   Third    man        True  NaN  Queenstown    no   True
389         1       2  female  17.00      0      0   12.0000        C  Second  woman       False  NaN   Cherbourg   yes   True
393         1       1  female  23.00      1      0  113.2750        C   First  woman       False    D   Cherbourg   yes  False
411         0       3    male    NaN      0      0    6.8583        Q   Third    man        True  NaN  Queenstown    no   True
412         1       1  female  33.00      1      0   90.0000        Q   First  woman       False    C  Queenstown   yes  False
420         0       3    male    NaN      0      0    7.8958        C   Third    man        True  NaN   Cherbourg    no   True
421         0       3    male  21.00      0      0    7.7333        Q   Third    man        True  NaN  Queenstown    no   True
428         0       3    male    NaN      0      0    7.7500        Q   Third    man        True  NaN  Queenstown    no   True
448         1       3  female   5.00      2      1   19.2583        C   Third  child       False  NaN   Cherbourg   yes  False
452         0       1    male  30.00      0      0   27.7500        C   First    man        True    C   Cherbourg    no   True
453         1       1    male  49.00      1      0   89.1042        C   First    man        True    C   Cherbourg   yes  False
455         1       3    male  29.00      0      0    7.8958        C   Third    man        True  NaN   Cherbourg   yes   True
459         0       3    male    NaN      0      0    7.7500        Q   Third    man        True  NaN  Queenstown    no   True
468         0       3    male    NaN      0      0    7.7250        Q   Third    man        True  NaN  Queenstown    no   True
469         1       3  female   0.75      2      1   19.2583        C   Third  child       False  NaN   Cherbourg   yes  False
473         1       2  female  23.00      0      0   13.7917        C  Second  woman       False    D   Cherbourg   yes   True
484         1       1    male  25.00      1      0   91.0792        C   First    man        True    B   Cherbourg   yes  False
487         0       1    male  58.00      0      0   29.7000        C   First    man        True    B   Cherbourg    no   True
493         0       1    male  71.00      0      0   49.5042        C   First    man        True  NaN   Cherbourg    no   True
495         0       3    male    NaN      0      0   14.4583        C   Third    man        True  NaN   Cherbourg    no   True
496         1       1  female  54.00      1      0   78.2667        C   First  woman       False    D   Cherbourg   yes  False
501         0       3  female  21.00      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown    no   True
502         0       3  female    NaN      0      0    7.6292        Q   Third  woman       False  NaN  Queenstown    no   True
505         0       1    male  18.00      1      0  108.9000        C   First    man        True    C   Cherbourg    no  False
510         1       3    male  29.00      0      0    7.7500        Q   Third    man        True  NaN  Queenstown   yes   True
513         1       1  female  54.00      1      0   59.4000        C   First  woman       False  NaN   Cherbourg   yes  False
517         0       3    male    NaN      0      0   24.1500        Q   Third    man        True  NaN  Queenstown    no   True
522         0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
523         1       1  female  44.00      0      1   57.9792        C   First  woman       False    B   Cherbourg   yes  False
524         0       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
525         0       3    male  40.50      0      0    7.7500        Q   Third    man        True  NaN  Queenstown    no   True
531         0       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
532         0       3    male  17.00      1      1    7.2292        C   Third    man        True  NaN   Cherbourg    no  False
533         1       3  female    NaN      0      2   22.3583        C   Third  woman       False  NaN   Cherbourg   yes  False
537         1       1  female  30.00      0      0  106.4250        C   First  woman       False  NaN   Cherbourg   yes   True
539         1       1  female  22.00      0      2   49.5000        C   First  woman       False    B   Cherbourg   yes  False
544         0       1    male  50.00      1      0  106.4250        C   First    man        True    C   Cherbourg    no  False
547         1       2    male    NaN      0      0   13.8625        C  Second    man        True  NaN   Cherbourg   yes   True
550         1       1    male  17.00      0      2  110.8833        C   First    man        True    C   Cherbourg   yes  False

## Görev 9: Yaşı 30 dan küçük ve kadın olan yolcuların tüm bilgilerini gösteriniz.

In [11]:
df.loc[(df["age"] < 30) & (df["sex"] == "female")].head()

    survived  pclass     sex   age  sibsp  parch     fare embarked   class    who  adult_male deck  embark_town alive  alone
2          1       3  female  26.0      0      0   7.9250        S   Third  woman       False  NaN  Southampton   yes   True
8          1       3  female  27.0      0      2  11.1333        S   Third  woman       False  NaN  Southampton   yes  False
9          1       2  female  14.0      1      0  30.0708        C  Second  child       False  NaN    Cherbourg   yes  False
10         1       3  female   4.0      1      1  16.7000        S   Third  child       False    G  Southampton   yes  False
14         0       3  female  14.0      0      0   7.8542        S   Third  child       False  NaN  Southampton    no   True

## Görev 10: Fare'i 500'den büyük veya yaşı 70 den büyük yolcuların bilgilerini gösteriniz.

In [12]:
df.loc[(df["fare"] > 500) | (df["age"] > 70)].head()

     survived  pclass     sex   age  sibsp  parch      fare embarked  class    who  adult_male deck  embark_town alive  alone
96          0       1    male  71.0      0      0   34.6542        C  First    man        True    A    Cherbourg    no   True
116         0       3    male  70.5      0      0    7.7500        Q  Third    man        True  NaN   Queenstown    no   True
258         1       1  female  35.0      0      0  512.3292        C  First  woman       False  NaN    Cherbourg   yes   True
493         0       1    male  71.0      0      0   49.5042        C  First    man        True  NaN    Cherbourg    no   True
630         1       1    male  80.0      0      0   30.0000        S  First    man        True    A  Southampton   yes   True

## Görev 11: Her bir değişkendeki boş değerlerin toplamını bulunuz.

In [13]:
df.isnull().sum()

# BONUS
df.loc[df.isnull().any(axis=1)]  # herhangi bir satırda eksik değer varsa gelir

# notnull => 1 tane de olsa dolu değer varsa satırı getirir
# (satır nasıl geliyor => axis=1) => axis=0 deseydik sütun olurdu
# df.loc[df.notnull().all(axis=1)]  # => tüm satırlar doluysa getir
# df.loc[df.notnull().any(axis=1)]  # => bir değer bile doluysa getir

     survived  pclass     sex    age  sibsp  parch      fare embarked   class    who  adult_male deck  embark_town alive  alone
0           0       3    male  22.00      1      0    7.2500        S   Third    man        True  NaN  Southampton    no  False
2           1       3  female  26.00      0      0    7.9250        S   Third  woman       False  NaN  Southampton   yes   True
4           0       3    male  35.00      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
5           0       3    male    NaN      0      0    8.4583        Q   Third    man        True  NaN   Queenstown    no   True
7           0       3    male   2.00      3      1   21.0750        S   Third  child       False  NaN  Southampton    no  False
8           1       3  female  27.00      0      2   11.1333        S   Third  woman       False  NaN  Southampton   yes  False
9           1       2  female  14.00      1      0   30.0708        C  Second  child       False  NaN    Cherbourg   yes  False
12          0       3    male  20.00      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
13          0       3    male  39.00      1      5   31.2750        S   Third    man        True  NaN  Southampton    no  False
14          0       3  female  14.00      0      0    7.8542        S   Third  child       False  NaN  Southampton    no   True
15          1       2  female  55.00      0      0   16.0000        S  Second  woman       False  NaN  Southampton   yes   True
16          0       3    male   2.00      4      1   29.1250        Q   Third  child       False  NaN   Queenstown    no  False
17          1       2    male    NaN      0      0   13.0000        S  Second    man        True  NaN  Southampton   yes   True
18          0       3  female  31.00      1      0   18.0000        S   Third  woman       False  NaN  Southampton    no  False
19          1       3  female    NaN      0      0    7.2250        C   Third  woman       False  NaN    Cherbourg   yes   True
20          0       2    male  35.00      0      0   26.0000        S  Second    man        True  NaN  Southampton    no   True
22          1       3  female  15.00      0      0    8.0292        Q   Third  child       False  NaN   Queenstown   yes   True
24          0       3  female   8.00      3      1   21.0750        S   Third  child       False  NaN  Southampton    no  False
25          1       3  female  38.00      1      5   31.3875        S   Third  woman       False  NaN  Southampton   yes  False
26          0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN    Cherbourg    no   True
28          1       3  female    NaN      0      0    7.8792        Q   Third  woman       False  NaN   Queenstown   yes   True
29          0       3    male    NaN      0      0    7.8958        S   Third    man        True  NaN  Southampton    no   True
30          0       1    male  40.00      0      0   27.7208        C   First    man        True  NaN    Cherbourg    no   True
31          1       1  female    NaN      1      0  146.5208        C   First  woman       False    B    Cherbourg   yes  False
32          1       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN   Queenstown   yes   True
33          0       2    male  66.00      0      0   10.5000        S  Second    man        True  NaN  Southampton    no   True
34          0       1    male  28.00      1      0   82.1708        C   First    man        True  NaN    Cherbourg    no  False
35          0       1    male  42.00      1      0   52.0000        S   First    man        True  NaN  Southampton    no  False
36          1       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN    Cherbourg   yes   True
37          0       3    male  21.00      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
38          0       3  female  18.00      2      0   18.0000        S   Third  woman       False  NaN  Southampton    no  False
39          1       3  female  14.00      1      0   11.2417        C   Third  child       False  NaN    Cherbourg   yes  False
40          0       3  female  40.00      1      0    9.4750        S   Third  woman       False  NaN  Southampton    no  False
41          0       2  female  27.00      1      0   21.0000        S  Second  woman       False  NaN  Southampton    no  False
42          0       3    male    NaN      0      0    7.8958        C   Third    man        True  NaN    Cherbourg    no   True
43          1       2  female   3.00      1      2   41.5792        C  Second  child       False  NaN    Cherbourg   yes  False
44          1       3  female  19.00      0      0    7.8792        Q   Third  woman       False  NaN   Queenstown   yes   True
45          0       3    male    NaN      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
46          0       3    male    NaN      1      0   15.5000        Q   Third    man        True  NaN   Queenstown    no  False
47          1       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN   Queenstown   yes   True
48          0       3    male    NaN      2      0   21.6792        C   Third    man        True  NaN    Cherbourg    no  False
49          0       3  female  18.00      1      0   17.8000        S   Third  woman       False  NaN  Southampton    no  False
50          0       3    male   7.00      4      1   39.6875        S   Third  child       False  NaN  Southampton    no  False
51          0       3    male  21.00      0      0    7.8000        S   Third    man        True  NaN  Southampton    no   True
53          1       2  female  29.00      1      0   26.0000        S  Second  woman       False  NaN  Southampton   yes  False
55          1       1    male    NaN      0      0   35.5000        S   First    man        True    C  Southampton   yes   True
56          1       2  female  21.00      0      0   10.5000        S  Second  woman       False  NaN  Southampton   yes   True
57          0       3    male  28.50      0      0    7.2292        C   Third    man        True  NaN    Cherbourg    no   True
58          1       2  female   5.00      1      2   27.7500        S  Second  child       False  NaN  Southampton   yes  False
59          0       3    male  11.00      5      2   46.9000        S   Third  child       False  NaN  Southampton    no  False
60          0       3    male  22.00      0      0    7.2292        C   Third    man        True  NaN    Cherbourg    no   True
61          1       1  female  38.00      0      0   80.0000      NaN   First  woman       False    B          NaN   yes   True
63          0       3    male   4.00      3      2   27.9000        S   Third  child       False  NaN  Southampton    no  False
64          0       1    male    NaN      0      0   27.7208        C   First    man        True  NaN    Cherbourg    no   True
65          1       3    male    NaN      1      1   15.2458        C   Third    man        True  NaN    Cherbourg   yes  False
67          0       3    male  19.00      0      0    8.1583        S   Third    man        True  NaN  Southampton    no   True
68          1       3  female  17.00      4      2    7.9250        S   Third  woman       False  NaN  Southampton   yes  False
69          0       3    male  26.00      2      0    8.6625        S   Third    man        True  NaN  Southampton    no  False
70          0       2    male  32.00      0      0   10.5000        S  Second    man        True  NaN  Southampton    no   True
71          0       3  female  16.00      5      2   46.9000        S   Third  woman       False  NaN  Southampton    no  False
72          0       2    male  21.00      0      0   73.5000        S  Second    man        True  NaN  Southampton    no   True
73          0       3    male  26.00      1      0   14.4542        C   Third    man        True  NaN    Cherbourg    no  False
74          1       3    male  32.00      0      0   56.4958        S   Third    man        True  NaN  Southampton   yes   True
76          0       3    male    NaN      0      0    7.8958        S   Third    man        True  NaN  Southampton    no   True
77          0       3    male    NaN      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
78          1       2    male   0.83      0      2   29.0000        S  Second  child       False  NaN  Southampton   yes  False
79          1       3  female  30.00      0      0   12.4750        S   Third  woman       False  NaN  Southampton   yes   True
80          0       3    male  22.00      0      0    9.0000        S   Third    man        True  NaN  Southampton    no   True
81          1       3    male  29.00      0      0    9.5000        S   Third    man        True  NaN  Southampton   yes   True
82          1       3  female    NaN      0      0    7.7875        Q   Third  woman       False  NaN   Queenstown   yes   True
83          0       1    male  28.00      0      0   47.1000        S   First    man        True  NaN  Southampton    no   True
84          1       2  female  17.00      0      0   10.5000        S  Second  woman       False  NaN  Southampton   yes   True
85          1       3  female  33.00      3      0   15.8500        S   Third  woman       False  NaN  Southampton   yes  False
86          0       3    male  16.00      1      3   34.3750        S   Third    man        True  NaN  Southampton    no  False
87          0       3    male    NaN      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
89          0       3    male  24.00      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
90          0       3    male  29.00      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
91          0       3    male  20.00      0      0    7.8542        S   Third    man        True  NaN  Southampton    no   True
93          0       3    male  26.00      1      2   20.5750        S   Third    man        True  NaN  Southampton    no  False
94          0       3    male  59.00      0      0    7.2500        S   Third    man        True  NaN  Southampton    no   True
95          0       3    male    NaN      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
98          1       2  female  34.00      0      1   23.0000        S  Second  woman       False  NaN  Southampton   yes  False
99          0       2    male  34.00      1      0   26.0000        S  Second    man        True  NaN  Southampton    no  False
100         0       3  female  28.00      0      0    7.8958        S   Third  woman       False  NaN  Southampton    no   True
101         0       3    male    NaN      0      0    7.8958        S   Third    man        True  NaN  Southampton    no   True
103         0       3    male  33.00      0      0    8.6542        S   Third    man        True  NaN  Southampton    no   True
104         0       3    male  37.00      2      0    7.9250        S   Third    man        True  NaN  Southampton    no  False
105         0       3    male  28.00      0      0    7.8958        S   Third    man        True  NaN  Southampton    no   True
106         1       3  female  21.00      0      0    7.6500        S   Third  woman       False  NaN  Southampton   yes   True
107         1       3    male    NaN      0      0    7.7750        S   Third    man        True  NaN  Southampton   yes   True
108         0       3    male  38.00      0      0    7.8958        S   Third    man        True  NaN  Southampton    no   True
109         1       3  female    NaN      1      0   24.1500        Q   Third  woman       False  NaN   Queenstown   yes  False
111         0       3  female  14.50      1      0   14.4542        C   Third  child       False  NaN    Cherbourg    no  False
112         0       3    male  22.00      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
113         0       3  female  20.00      1      0    9.8250        S   Third  woman       False  NaN  Southampton    no  False
114         0       3  female  17.00      0      0   14.4583        C   Third  woman       False  NaN    Cherbourg    no   True
115         0       3    male  21.00      0      0    7.9250        S   Third    man        True  NaN  Southampton    no   True
116         0       3    male  70.50      0      0    7.7500        Q   Third    man        True  NaN   Queenstown    no   True
117         0       2    male  29.00      1      0   21.0000        S  Second    man        True  NaN  Southampton    no  False
119         0       3  female   2.00      4      2   31.2750        S   Third  child       False  NaN  Southampton    no  False
120         0       2    male  21.00      2      0   73.5000        S  Second    man        True  NaN  Southampton    no  False
121         0       3    male    NaN      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
122         0       2    male  32.50      1      0   30.0708        C  Second    man        True  NaN    Cherbourg    no  False
125         1       3    male  12.00      1      0   11.2417        C   Third  child       False  NaN    Cherbourg   yes  False
126         0       3    male    NaN      0      0    7.7500        Q   Third    man        True  NaN   Queenstown    no   True
127         1       3    male  24.00      0      0    7.1417        S   Third    man        True  NaN  Southampton   yes   True
128         1       3  female    NaN      1      1   22.3583        C   Third  woman       False    F    Cherbourg   yes  False
129         0       3    male  45.00      0      0    6.9750        S   Third    man        True  NaN  Southampton    no   True
130         0       3    male  33.00      0      0    7.8958        C   Third    man        True  NaN    Cherbourg    no   True
131         0       3    male  20.00      0      0    7.0500        S   Third    man        True  NaN  Southampton    no   True
132         0       3  female  47.00      1      0   14.5000        S   Third  woman       False  NaN  Southampton    no  False
133         1       2  female  29.00      1      0   26.0000        S  Second  woman       False  NaN  Southampton   yes  False
134         0       2    male  25.00      0      0   13.0000        S  Second    man        True  NaN  Southampton    no   True
135         0       2    male  23.00      0      0   15.0458        C  Second    man        True  NaN    Cherbourg    no   True
138         0       3    male  16.00      0      0    9.2167        S   Third    man        True  NaN  Southampton    no   True
140         0       3  female    NaN      0      2   15.2458        C   Third  woman       False  NaN    Cherbourg    no  False
141         1       3  female  22.00      0      0    7.7500        S   Third  woman       False  NaN  Southampton   yes   True
142         1       3  female  24.00      1      0   15.8500        S   Third  woman       False  NaN  Southampton   yes  False
143         0       3    male  19.00      0      0    6.7500        Q   Third    man        True  NaN   Queenstown    no   True
144         0       2    male  18.00      0      0   11.5000        S  Second    man        True  NaN  Southampton    no   True
145         0       2    male  19.00      1      1   36.7500        S  Second    man        True  NaN  Southampton    no  False
146         1       3    male  27.00      0      0    7.7958        S   Third    man        True  NaN  Southampton   yes   True
147         0       3  female   9.00      2      2   34.3750        S   Third  child       False  NaN  Southampton    no  False
149         0       2    male  42.00      0      0   13.0000        S  Second    man        True  NaN  Southampton    no   True
150         0       2    male  51.00      0      0   12.5250        S  Second    man        True  NaN  Southampton    no   True
152         0       3    male  55.50      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
153         0       3    male  40.50      0      2   14.5000        S   Third    man        True  NaN  Southampton    no  False
154         0       3    male    NaN      0      0    7.3125        S   Third    man        True  NaN  Southampton    no   True
155         0       1    male  51.00      0      1   61.3792        C   First    man        True  NaN    Cherbourg    no  False
156         1       3  female  16.00      0      0    7.7333        Q   Third  woman       False  NaN   Queenstown   yes   True
157         0       3    male  30.00      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
158         0       3    male    NaN      0      0    8.6625        S   Third    man        True  NaN  Southampton    no   True
159         0       3    male    NaN      8      2   69.5500        S   Third    man        True  NaN  Southampton    no  False
160         0       3    male  44.00      0      1   16.1000        S   Third    man        True  NaN  Southampton    no  False
161         1       2  female  40.00      0      0   15.7500        S  Second  woman       False  NaN  Southampton   yes   True
162         0       3    male  26.00      0      0    7.7750        S   Third    man        True  NaN  Southampton    no   True
163         0       3    male  17.00      0      0    8.6625        S   Third    man        True  NaN  Southampton    no   True
164         0       3    male   1.00      4      1   39.6875        S   Third  child       False  NaN  Southampton    no  False
165         1       3    male   9.00      0      2   20.5250        S   Third  child       False  NaN  Southampton   yes  False
166         1       1  female    NaN      0      1   55.0000        S   First  woman       False    E  Southampton   yes  False
167         0       3  female  45.00      1      4   27.9000        S   Third  woman       False  NaN  Southampton    no  False
168         0       1    male    NaN      0      0   25.9250        S   First    man        True  NaN  Southampton    no   True
169         0       3    male  28.00      0      0   56.4958        S   Third    man        True  NaN  Southampton    no   True
171         0       3    male   4.00      4      1   29.1250        Q   Third  child       False  NaN   Queenstown    no  False
172         1       3  female   1.00      1      1   11.1333        S   Third  child       False  NaN  Southampton   yes  False
173         0       3    male  21.00      0      0    7.9250        S   Third    man        True  NaN  Southampton    no   True
175         0       3    male  18.00      1      1    7.8542        S   Third    man        True  NaN  Southampton    no  False
176         0       3    male    NaN      3      1   25.4667        S   Third    man        True  NaN  Southampton    no  False
178         0       2    male  30.00      0      0   13.0000        S  Second    man        True  NaN  Southampton    no   True
179         0       3    male  36.00      0      0    0.0000        S   Third    man        True  NaN  Southampton    no   True
180         0       3  female    NaN      8      2   69.5500        S   Third  woman       False  NaN  Southampton    no  False
181         0       2    male    NaN      0      0   15.0500        C  Second    man        True  NaN    Cherbourg    no   True
182         0       3    male   9.00      4      2   31.3875        S   Third  child       False  NaN  Southampton    no  False
184         1       3  female   4.00      0      2   22.0250        S   Third  child       False  NaN  Southampton   yes  False
185         0       1    male    NaN      0      0   50.0000        S   First    man        True    A  Southampton    no   True

## Görev 12: who değişkenini dataframe'den düşürün.

In [14]:
df.drop("who", axis=1, inplace=True)
# df = df.drop("who", axis=1)  # inplace=True'nun yaptığı

## Görev 13: deck değikenindeki boş değerleri deck değişkenin en çok tekrar eden değeri (mode) ile doldurunuz.

In [15]:
df["deck"].mode()
type(df["deck"].mode())
df["deck"].mode()[0]  # çıktısı pd.series
type(df["deck"].mode()[0])  # str

df["deck"].fillna(df["deck"].mode()[0], inplace=True)
# df["deck"] = df["deck"].fillna(df["deck"].mode()[0])  # => inplace=True'nun yaptığı
df["deck"].isnull().sum()
df.deck.tail()

886    C
887    B
888    C
889    C
890    C
Name: deck, dtype: category
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

## Görev 14: age değikenindeki boş değerleri age değişkenin medyanı ile doldurun.

In [16]:
df["age"].fillna(df["age"].median(), inplace=True)
df["age"].isnull().sum()

np.int64(0)

## Görev 15: survived değişkeninin Pclass ve Cinsiyet değişkenleri kırılımınında sum, count, mean değerlerini bulunuz.

In [17]:
df.groupby(["pclass", "sex"]).agg({"survived": ["sum","count","mean"]})  # Not: orijinal script'te "Pclass" (buyuk P) kullanilmisti; gercek kolon adi kucuk harfli "pclass".

df.pivot_table("survived", ["pclass", "sex"], aggfunc=["sum", "count", "mean"])  # Not: orijinal script'te "Pcclass" yazim hatasi vardi, doğrusu "pclass".

                   sum    count      mean
              survived survived  survived
pclass sex
1      female       91       94  0.968085
       male         45      122  0.368852
2      female       70       76  0.921053
       male         17      108  0.157407
3      female       72      144  0.500000
       male         47      347  0.135447

## Görev 16:  30 yaşın altında olanlar 1, 30'a eşit ve üstünde olanlara 0 verecek bir fonksiyon yazınız.

Yazdığınız fonksiyonu kullanarak titanik veri setinde age_flag adında bir değişken oluşturunuz. (apply ve lambda yapılarını kullanınız)

In [18]:
def age_30(age):
    if age < 30:
        return 1
    else:
        return 0

df["age_flag"] = df["age"].apply(lambda x: age_30(x))

# 2. YOL
# fonksiyon tanımlamadan
df["age_flag"] = df["age"].apply(lambda x: 1 if x < 30 else 0)

# # 3. YOL - apply/lambda kullanmadan
# df["age_flag_2"] = np.where(df["age"] < 30, 1, 0)

## Görev 17: Seaborn kütüphanesi içerisinden Tips veri setini tanımlayınız.

In [19]:
df = sns.load_dataset("tips")
df.head()
df.shape

(244, 7)

## Görev 18: Time değişkeninin kategorilerine (Dinner, Lunch) göre total_bill  değerlerinin toplamını, min, max ve ortalamasını bulunuz.

In [20]:
df.groupby("time").agg({"total_bill": ["sum","min","mean","max"]})

df.pivot_table("total_bill", "time", aggfunc=["min", "max", "mean"])

C:\Users\ONI\AppData\Local\Temp\ipykernel_30252\3036675425.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("time").agg({"total_bill": ["sum","min","mean","max"]})
C:\Users\ONI\AppData\Local\Temp\ipykernel_30252\3036675425.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table("total_bill", "time", aggfunc=["min", "max", "mean"])
C:\Users\ONI\AppData\Local\Temp\ipykernel_30252\3036675425.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table("total_bill", "time", aggfunc=["min", "max", "mean"])
C:\Users\ONI\AppData\Local\Temp\ipykernel_30252\3036675425.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table("total_bill", "time", aggfunc=["min", "max", "mean"])

              min        max       mean
       total_bill total_bill total_bill
time
Lunch        7.51      43.11  17.168676
Dinner       3.07      50.81  20.797159

## Görev 19: Günlere ve time göre total_bill değerlerinin toplamını, min, max ve ortalamasını bulunuz.

In [21]:
df.groupby(["day", "time"]).agg({"total_bill": ["sum","min","mean","max"]})

df.pivot_table(index=["day", "time"], values="total_bill", aggfunc=["sum","min","mean","max"])

# df.loc[(df["day"] == "Sat") & (df["time"] == "Lunch")]  # Empty DataFrame
# df.loc[(df["day"] == "Sun") & (df["time"] == "Lunch")]  # Empty DataFrame

C:\Users\ONI\AppData\Local\Temp\ipykernel_30252\1064936916.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["day", "time"]).agg({"total_bill": ["sum","min","mean","max"]})
C:\Users\ONI\AppData\Local\Temp\ipykernel_30252\1064936916.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index=["day", "time"], values="total_bill", aggfunc=["sum","min","mean","max"])
C:\Users\ONI\AppData\Local\Temp\ipykernel_30252\1064936916.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index=["day", "time"], values="total_bill", aggfunc=["sum","min","mean","max"])
C:\Users\ONI\AppData\Local\Temp\ipykernel_30252\1064936916.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index=["day", "time"], values="total_bill", aggfunc=["sum","min","mean","max"])
C:\Users\ONI\AppData\Local\Temp\ipykernel_30252\1064936916.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index=["day", "time"], values="total_bill", aggfunc=["sum","min","mean","max"])

                   sum        min       mean        max
            total_bill total_bill total_bill total_bill
day  time
Thur Lunch     1077.55       7.51  17.664754      43.11
     Dinner      18.78      18.78  18.780000      18.78
Fri  Lunch       89.92       8.58  12.845714      16.27
     Dinner     235.96       5.75  19.663333      40.17
Sat  Lunch        0.00        NaN        NaN        NaN
     Dinner    1778.40       3.07  20.441379      50.81
Sun  Lunch        0.00        NaN        NaN        NaN
     Dinner    1627.16       7.25  21.410000      48.17

## Görev 20:Lunch zamanına ve kadın müşterilere ait total_bill ve tip  değerlerinin day'e göre toplamını, min, max ve ortalamasını bulunuz.

In [22]:
df.loc[(df["time"] == "Lunch") & (df["sex"] == "Female")].groupby("day").agg({"total_bill": ["sum","min","max","mean"],
                                                                           "tip": ["sum","min","max","mean"]})

C:\Users\ONI\AppData\Local\Temp\ipykernel_30252\3147127436.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.loc[(df["time"] == "Lunch") & (df["sex"] == "Female")].groupby("day").agg({"total_bill": ["sum","min","max","mean"],

     total_bill                            tip
            sum    min    max      mean    sum   min   max      mean
day
Thur     516.11   8.35  43.11  16.64871  79.42  1.25  5.17  2.561935
Fri       55.76  10.09  16.27  13.94000  10.98  2.00  3.48  2.745000
Sat        0.00    NaN    NaN       NaN   0.00   NaN   NaN       NaN
Sun        0.00    NaN    NaN       NaN   0.00   NaN   NaN       NaN

## Görev 21: size'i 3'ten küçük, total_bill'i 10'dan büyük olan siparişlerin ortalaması nedir?

In [23]:
df.loc[(df["size"] < 3) & (df["total_bill"] > 10), "total_bill"].mean()  # 17.184965034965035
# df[(df["size"] < 3) & (df["total_bill"] > 10)]["total_bill"].mean()

np.float64(17.184965034965035)

## Görev 22: total_bill_tip_sum adında yeni bir değişken oluşturun. Her bir müşterinin ödediği totalbill ve tip in toplamını versin.

In [24]:
df["total_bill_tip_sum"] = df["total_bill"] + df["tip"]
df.head()

   total_bill   tip     sex smoker  day    time  size  total_bill_tip_sum
0       16.99  1.01  Female     No  Sun  Dinner     2               18.00
1       10.34  1.66    Male     No  Sun  Dinner     3               12.00
2       21.01  3.50    Male     No  Sun  Dinner     3               24.51
3       23.68  3.31    Male     No  Sun  Dinner     2               26.99
4       24.59  3.61  Female     No  Sun  Dinner     4               28.20

## Görev 23: total_bill_tip_sum değişkenine göre büyükten küçüğe sıralayınız ve ilk 30 kişiyi yeni bir dataframe'e atayınız.

In [25]:
new_df = df.sort_values("total_bill_tip_sum", ascending=False)[:30]
new_df.shape
new_df.head()

# 2. YOL
new_df = df.sort_values("total_bill_tip_sum", ascending=False).head(30)
new_df.shape

(30, 8)

## BONUS 1

Total_bill değişkeninin kadın ve erkek için ayrı ayrı ortalamasını bulun.
Bulduğunuz ortalamaların altında olanlara 0, üstünde ve eşit olanlara bir verildiği yeni bir total_bill_flag değişkeni oluşturun.
Dikkat !! Female olanlar için kadınlar için bulunan ortalama dikkate alıncak, male için ise erkekler için bulunan ortalama.
parametre olarak cinsiyet ve total_bill alan bir fonksiyon yazarak başlayın. (If-else koşulları içerecek)

In [26]:
# total bill'in kadınlar ve erkekler için ortalaması

f_avg = df[df["sex"]=="Female"]["total_bill"].mean() # 18.056896551724133
m_avg = df[df["sex"]=="Male"]["total_bill"].mean() # 20.744076433121016

def func(sex,total_bill):
    if sex=="Female":
        if total_bill < f_avg:
            return 0
        else:
            return 1
    else:
        if total_bill < m_avg:
            return 0
        else:
            return 1

df["total_bill_flag"] = df[["sex","total_bill"]].apply(lambda x: func(x["sex"],x["total_bill"]),axis=1)

## BONUS 2

total_bill_flag değişkenini kullanarak cinsiyetlere göre ortalamanın altında ve üstünde olanların sayısını gözlemleyin.

In [27]:
df.groupby(["sex","total_bill_flag"]).agg({"total_bill_flag":"count"})

C:\Users\ONI\AppData\Local\Temp\ipykernel_30252\2592007173.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["sex","total_bill_flag"]).agg({"total_bill_flag":"count"})

                        total_bill_flag
sex    total_bill_flag
Male   0                             95
       1                             62
Female 0                             54
       1                             33

## Agg. örnekler

In [28]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'Animal': ['Falcon', 'Falcon', "Falcon","Falcon",
                               'Parrot', 'Parrot'],
                   'Max Speed': [380., np.nan, np.nan, 45,24., 26.]})

# agg_df = df.groupby("Animal")["Max Speed"].mean().reset_index()
# agg_df.columns = ["animal", "avg_max_speed"]
# agg_df = agg_df.rename({"Max Speed":"avg_max_speed"}, axis=1)
# df.groupby("Animal").agg(avg_max_speed=("Max Speed", "mean")).reset_index()



# dropna argümanının farkı
import pandas as pd
import numpy as np

# Örnek veri oluşturma
data = {
    'kategori': ['A', 'B', 'A', np.nan, 'B', 'C', np.nan],
    'deger': [10, 20, 30, 40, np.nan, 60, 100]
}

df = pd.DataFrame(data)

# dropna=True örneği
grouped_dropna_true = df.groupby('kategori', dropna=True).agg(
    toplam_deger=('deger', 'sum'),
    ortalama_deger=('deger', 'mean')
)

# dropna=False örneği
grouped_dropna_false = df.groupby('kategori', dropna=False).agg(
    toplam_deger=('deger', 'sum'),
    ortalama_deger=('deger', 'mean')
)

print("dropna=True ile gruplandırma:")
print(grouped_dropna_true)
print("\ndropna=False ile gruplandırma:")
print(grouped_dropna_false)

dropna=True ile gruplandırma:
          toplam_deger  ortalama_deger
kategori
A                 40.0            20.0
B                 20.0            20.0
C                 60.0            60.0

dropna=False ile gruplandırma:
          toplam_deger  ortalama_deger
kategori
A                 40.0            20.0
B                 20.0            20.0
C                 60.0            60.0
NaN              140.0            70.0